# Data Wrangling

In [1]:
import pandas as pd

In [2]:
# Cargar el archivo CSV
df = pd.read_csv("../data/raw/Airbnb_Data.csv")

## Valores Nulos

In [3]:
# Ver los valores nulos 
df.isnull().sum()

id                            0
log_price                     0
property_type                 0
room_type                     0
amenities                     0
accommodates                  0
bathrooms                   200
bed_type                      0
cancellation_policy           0
cleaning_fee                  0
city                          0
description                   0
first_review              15864
host_has_profile_pic        188
host_identity_verified      188
host_response_rate        18299
host_since                  188
instant_bookable              0
last_review               15827
latitude                      0
longitude                     0
name                          0
neighbourhood              6872
number_of_reviews             0
review_scores_rating      16722
thumbnail_url              8216
zipcode                     966
bedrooms                     91
beds                        131
dtype: int64

In [4]:
# Cambiar los nulos por -1
df["bathrooms"] = df["bathrooms"].fillna(-1)

In [5]:
# Cambiar los nulos por -1
df["host_has_profile_pic"] = df["host_has_profile_pic"].fillna(-1)

In [6]:
df["host_identity_verified"] = df["host_identity_verified"].fillna(-1)

In [7]:
# pasar de 20% a 0.20
df["host_response_rate"] = df["host_response_rate"].str.replace("%","").astype(float) / 100

In [8]:
# Cambiar los nulos por -1
df["host_response_rate"] = df["host_response_rate"].fillna(-1)

In [9]:
# Reemplazar los nulos por -1
df["review_scores_rating"] = df["review_scores_rating"].fillna(-1)

In [10]:
# Confirmar si existen valores decimales
df["bedrooms"].dropna().apply(lambda x: x.is_integer()).unique()

array([ True])

In [11]:
# Reemplazar los nulos por -1
df["bedrooms"] = df["bedrooms"].fillna(-1)

In [12]:
df['beds'] = df['beds'].fillna(-1)

In [13]:
df["beds"].dropna().apply(lambda x: x.is_integer()).unique()

array([ True])

In [14]:
# Transforma la columan beds y bathrooms a entero
df["bedrooms"] = df["bedrooms"].astype(int)
df["beds"] = df["beds"].astype(int)

In [15]:
df["beds"].unique()

array([ 1,  3,  2,  7,  4,  6,  5, -1, 10,  8, 16,  9, 13, 12, 11, 14, 15,
        0, 18])

In [16]:
# Cambiar los nulos por -1
df["bathrooms"] = df["bathrooms"].fillna(-1)

In [17]:
# Transforma a booleano la columna instant_bookable
df["instant_bookable"] = df["instant_bookable"].map({"t":True, "f":False})

In [18]:
df["instant_bookable"].unique()

array([False,  True])

In [19]:
df.columns

Index(['id', 'log_price', 'property_type', 'room_type', 'amenities',
       'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy',
       'cleaning_fee', 'city', 'description', 'first_review',
       'host_has_profile_pic', 'host_identity_verified', 'host_response_rate',
       'host_since', 'instant_bookable', 'last_review', 'latitude',
       'longitude', 'name', 'neighbourhood', 'number_of_reviews',
       'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds'],
      dtype='object')

In [20]:
df_procesado = df[['log_price','property_type','room_type','amenities','accommodates','bathrooms','bed_type','cancellation_policy','cleaning_fee','city', 'host_has_profile_pic','host_identity_verified','host_response_rate','instant_bookable','latitude','longitude','number_of_reviews','review_scores_rating','bedrooms','beds']]

In [21]:
df_procesado.isnull().sum()

log_price                 0
property_type             0
room_type                 0
amenities                 0
accommodates              0
bathrooms                 0
bed_type                  0
cancellation_policy       0
cleaning_fee              0
city                      0
host_has_profile_pic      0
host_identity_verified    0
host_response_rate        0
instant_bookable          0
latitude                  0
longitude                 0
number_of_reviews         0
review_scores_rating      0
bedrooms                  0
beds                      0
dtype: int64

In [22]:
df_procesado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   log_price               74111 non-null  float64
 1   property_type           74111 non-null  object
 2   room_type               74111 non-null  object
 3   amenities               74111 non-null  object
 4   accommodates            74111 non-null  int64
 5   bathrooms               74111 non-null  float64
 6   bed_type                74111 non-null  object
 7   cancellation_policy     74111 non-null  object
 8   cleaning_fee            74111 non-null  bool
 9   city                    74111 non-null  object
 10  host_has_profile_pic    74111 non-null  object
 11  host_identity_verified  74111 non-null  object
 12  host_response_rate      74111 non-null  float64
 13  instant_bookable        74111 non-null  bool
 14  latitude                74111 non-null  float64
 15  longitude               74111 non-null  float64
 16  number_of_reviews       74111 non-null  int64
 17  review_scores_rating    74111 non-null  float64
 18  bedrooms                74111 non-null  int64
 19  beds                    74111 non-null  int64
dtypes: bool(2), float64(6), int64(4), object(8)
memory usage: 10.3+ MB

In [23]:
# Compara el tamaño del dataframe original con el procesado
print(df.shape)
print(df_procesado.shape)

(74111, 29)
(74111, 20)

In [24]:
df_procesado.shape

(74111, 20)

## Outliers

In [25]:
# Función para eliminar outliers Q1 - 1.5 * IQR y Q3 + 1.5 * IQR
def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] > lower_bound) & (df[column] < upper_bound)]

In [26]:
df_procesado

,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_has_profile_pic,host_identity_verified,host_response_rate,instant_bookable,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
0,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,NYC,t,t,-1.0,False,40.696524,-73.991617,2,100.0,1,1
1,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,NYC,t,f,1.0,True,40.766115,-73.989040,6,93.0,3,3
2,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,NYC,t,t,1.0,True,40.808110,-73.943756,10,92.0,1,3
3,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,SF,t,t,-1.0,False,37.772004,-122.431619,0,-1.0,2,2
4,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,DC,t,t,1.0,True,38.925627,-77.034596,4,40.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,4.605170,Apartment,Private room,{},1,1.0,Real Bed,flexible,False,NYC,t,t,-1.0,False,40.709025,-73.939405,0,-1.0,1,1
74107,5.043425,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,2.0,Real Bed,moderate,True,LA,t,f,1.0,False,33.871549,-118.396053,16,93.0,2,4
74108,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1.0,Real Bed,moderate,True,NYC,t,t,1.0,True,40.706749,-73.942377,43,94.0,2,2
74109,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1.0,Real Bed,strict,True,NYC,t,f,1.0,True,40.738535,-74.000157,0,-1.0,0,2
74110,4.852030,Boat,Entire home/apt,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",4,1.0,Real Bed,moderate,False,LA,t,t,1.0,False,33.761096,-118.192409,205,96.0,1,2

In [27]:
df_procesado = remove_outliers(df_procesado, "log_price")

In [28]:
df_procesado.shape

(72579, 20)

In [29]:
df_procesado = remove_outliers(df_procesado, "number_of_reviews")

In [30]:
df_procesado.shape

(64765, 20)

In [31]:
df_procesado = remove_outliers(df_procesado, "beds")

In [32]:
df_procesado.shape

(60245, 20)

In [33]:
df_procesado = remove_outliers(df_procesado, "accommodates")

In [34]:
df_procesado.shape

(59463, 20)

In [35]:
df_procesado = remove_outliers(df_procesado, "review_scores_rating")

In [36]:
df_procesado.shape

(59463, 20)

In [37]:
df_procesado.shape

(59463, 20)

In [38]:
df_procesado

,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_has_profile_pic,host_identity_verified,host_response_rate,instant_bookable,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
0,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,NYC,t,t,-1.00,False,40.696524,-73.991617,2,100.0,1,1
2,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,NYC,t,t,1.00,True,40.808110,-73.943756,10,92.0,1,3
4,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,DC,t,t,1.00,True,38.925627,-77.034596,4,40.0,0,1
5,4.442651,Apartment,Private room,"{TV,""Wireless Internet"",Heating,""Smoke detecto...",2,1.0,Real Bed,strict,True,SF,t,t,1.00,True,37.753164,-122.429526,3,100.0,1,1
6,4.418841,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",3,1.0,Real Bed,moderate,True,LA,t,f,1.00,True,33.980454,-118.462821,15,97.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74104,4.356709,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",2,1.0,Real Bed,strict,True,Chicago,t,t,1.00,False,41.909067,-87.623046,6,100.0,1,1
74105,4.248495,House,Private room,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,LA,t,t,0.75,False,34.092640,-118.343921,36,91.0,1,1
74106,4.605170,Apartment,Private room,{},1,1.0,Real Bed,flexible,False,NYC,t,t,-1.00,False,40.709025,-73.939405,0,-1.0,1,1
74108,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1.0,Real Bed,moderate,True,NYC,t,t,1.00,True,40.706749,-73.942377,43,94.0,2,2
74109,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1.0,Real Bed,strict,True,NYC,t,f,1.00,True,40.738535,-74.000157,0,-1.0,0,2

In [39]:
df_procesado.to_csv("../data/processed/Airbnb_Data.csv", index=False)